apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kustom-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GitDemis/istiando.git
    path: istio-multi/overlays/cluster1
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
