apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ztunnel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: ztunnel
    targetRevision: 1.27.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        global:
          network: network1
        multiCluster:
          clusterName: cluster1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true